"""Recreate all tables

Revision ID: 9bc730f98bf7
Revises: aa7ccb9970f4
Create Date: 2025-06-29 19:40:46.264401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bc730f98bf7'
down_revision: Union[str, Sequence[str], None] = 'aa7ccb9970f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'color')
    # ### end Alembic commands ###
