"""Add item, quantity, location to Transaction

Revision ID: aa7ccb9970f4
Revises: aba7fc35d6c2
Create Date: 2025-06-28 13:17:49.818404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7ccb9970f4'
down_revision: Union[str, Sequence[str], None] = 'aba7fc35d6c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('item', sa.String(length=255), nullable=False))
    op.add_column('transactions', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'location')
    op.drop_column('transactions', 'quantity')
    op.drop_column('transactions', 'item')
    # ### end Alembic commands ###
